name: Deploy to PyPI

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  deployment:
    uses: ./.github/workflows/publish.yml
    with:
      ENVIRONMENT: production
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
