name: Deploy to TestPyPI

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+-test']

jobs:
  deployment:
    uses: ./.github/workflows/publish.yml
    with:
      ENVIRONMENT: development
      pypi_repository_url: https://test.pypi.org/legacy/
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      
