name: Deploy to PyPI

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  deployment:
    name: Deploy Python packages to PyPI
    uses: ./.github/workflows/publish.yml@main
      with:
        ENVIRONMENT: production
        pypi_token: ${{ secrets.PYPI_TOKEN }}
